cc_library(
    name = "protocol",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//include/protocol:protocol_headers",
        "@boost.asio//:boost.asio"
        ],
)
