cc_library(
    name ="core",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//include/core:core_headers",
        
        "@boost.asio//:boost.asio"
        ], 
)